"""empty message

Revision ID: d6a40e2c771
Revises: None
Create Date: 2014-12-08 17:11:46.071494

"""

# revision identifiers, used by Alembic.
revision = 'd6a40e2c771'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
