"""empty message

Revision ID: 1271e5867432
Revises: 4ccfe9c1b8fa
Create Date: 2014-12-28 20:34:44.091058

"""

# revision identifiers, used by Alembic.
revision = '1271e5867432'
down_revision = '4ccfe9c1b8fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    #op.drop_column('matches', 'actual_winner')
    #op.drop_column('matches', 'match_ft_score')
    #op.drop_column('matches', 'played')
    #op.drop_column('messages', 'author_id')
    #op.add_column('prediction_modules', sa.Column('weight', sa.Float(), nullable=True))
    #op.drop_column('prediction_modules', 'default_weight')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_modules', sa.Column('default_weight', sa.FLOAT(), nullable=True))
    op.drop_column('prediction_modules', 'weight')
    op.add_column('messages', sa.Column('author_id', sa.INTEGER(), nullable=True))
    op.add_column('matches', sa.Column('played', sa.BOOLEAN(), nullable=True))
    op.add_column('matches', sa.Column('match_ft_score', sa.VARCHAR(length=8), nullable=True))
    op.add_column('matches', sa.Column('actual_winner', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
