"""empty message

Revision ID: 1391ee426d4
Revises: 5254a0cc19e9
Create Date: 2014-12-23 12:49:41.368750

"""

# revision identifiers, used by Alembic.
revision = '1391ee426d4'
down_revision = '5254a0cc19e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('matches', 'actual_winner')
    #op.drop_column('matches', 'match_ft_score')
    #op.drop_column('messages', 'author_id')
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('author_id', sa.INTEGER(), nullable=True))
    op.add_column('matches', sa.Column('match_ft_score', sa.VARCHAR(length=8), nullable=True))
    op.add_column('matches', sa.Column('actual_winner', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
