"""empty message

Revision ID: 182d5f84e276
Revises: 1271e5867432
Create Date: 2015-02-15 16:20:58.923496

"""

# revision identifiers, used by Alembic.
revision = '182d5f84e276'
down_revision = '1271e5867432'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savedforlater', sa.Column('user_hunch', sa.Float(), nullable=True))
    op.add_column('savedforlater', sa.Column('weight_user_hunch', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savedforlater', 'weight_user_hunch')
    op.drop_column('savedforlater', 'user_hunch')
    op.add_column('prediction_modules', sa.Column('default_weight', sa.FLOAT(), nullable=True))
    op.add_column('messages', sa.Column('author_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['author_id'], ['id'])
    op.add_column('matches', sa.Column('played', sa.BOOLEAN(), nullable=True))
    op.add_column('matches', sa.Column('match_ft_score', sa.VARCHAR(length=8), nullable=True))
    op.add_column('matches', sa.Column('actual_winner', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'matches', 'teams', ['actual_winner'], ['id'])
    ### end Alembic commands ###
