"""empty message

Revision ID: 1a7c4fef6098
Revises: 48c56b74f757
Create Date: 2014-12-22 15:24:25.929160

"""

# revision identifiers, used by Alembic.
revision = '1a7c4fef6098'
down_revision = '48c56b74f757'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    #op.drop_column('matches', 'actual_winner')
    #op.drop_column('matches', 'match_ft_score')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('match_ft_score', sa.VARCHAR(length=8), nullable=True))
    op.add_column('matches', sa.Column('actual_winner', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
