"""empty message

Revision ID: 20d594324742
Revises: 44e2a19af084
Create Date: 2014-11-20 12:30:39.451805

"""

# revision identifiers, used by Alembic.
revision = '20d594324742'
down_revision = '44e2a19af084'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('played', sa.Boolean(), nullable=True),
    sa.Column('hometeam_id', sa.Integer(), nullable=False),
    sa.Column('awayteam_id', sa.Integer(), nullable=False),
    sa.Column('hometeam_score', sa.Integer(), nullable=True),
    sa.Column('awayteam_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['awayteam_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['hometeam_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    ### end Alembic commands ###
