"""empty message

Revision ID: 239eed8ebbba
Revises: 32e121b55143
Create Date: 2014-12-20 16:50:30.467051

"""

# revision identifiers, used by Alembic.
revision = '239eed8ebbba'
down_revision = '32e121b55143'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_performance', 'id',
               existing_type=sa.INTEGER())
    op.alter_column('user_performance', 'user_id',
               existing_type=sa.INTEGER())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_performance', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_performance', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
