"""empty message

Revision ID: 27570cccdafb
Revises: f71d76b12be
Create Date: 2014-12-08 17:39:10.992039

"""

# revision identifiers, used by Alembic.
revision = '27570cccdafb'
down_revision = 'f71d76b12be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'league_position')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('league_position', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
