"""empty message

Revision ID: 29a809880da2
Revises: 20d594324742
Create Date: 2014-11-20 18:21:52.127003

"""

# revision identifiers, used by Alembic.
revision = '29a809880da2'
down_revision = '20d594324742'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
