"""empty message

Revision ID: 29ee771d5245
Revises: 403f8fa43073
Create Date: 2014-11-07 17:20:40.513606

"""

# revision identifiers, used by Alembic.
revision = '29ee771d5245'
down_revision = '403f8fa43073'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
