"""empty message

Revision ID: 2a3ecccec26a
Revises: 29a809880da2
Create Date: 2014-11-20 18:22:05.165513

"""

# revision identifiers, used by Alembic.
revision = '2a3ecccec26a'
down_revision = '29a809880da2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
