"""empty message

Revision ID: 2b91a8d76a7
Revises: 1a7c4fef6098
Create Date: 2014-12-22 15:38:28.217294

"""

# revision identifiers, used by Alembic.
revision = '2b91a8d76a7'
down_revision = '1a7c4fef6098'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    #op.drop_column('matches', 'actual_winner')
    #op.drop_column('matches', 'match_ft_score')
    #op.add_column('messages', sa.Column('addressee_id', sa.Integer(), nullable=True))
    #op.drop_column('messages', 'author_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('author_id', sa.INTEGER(), nullable=True))
    op.drop_column('messages', 'addressee_id')
    op.add_column('matches', sa.Column('match_ft_score', sa.VARCHAR(length=8), nullable=True))
    op.add_column('matches', sa.Column('actual_winner', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
