"""empty message

Revision ID: 2ca2bc7d7374
Revises: 42760c4629df
Create Date: 2014-12-18 16:44:29.681676

"""

# revision identifiers, used by Alembic.
revision = '2ca2bc7d7374'
down_revision = '42760c4629df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('league_position', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
