"""empty message

Revision ID: 313b0da7226d
Revises: 4e025d7cb728
Create Date: 2014-12-09 12:26:18.616439

"""

# revision identifiers, used by Alembic.
revision = '313b0da7226d'
down_revision = '4e025d7cb728'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'league_position')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('league_position', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
