"""empty message

Revision ID: 32e121b55143
Revises: 46dd0ebbba0e
Create Date: 2014-12-20 16:39:48.566787

"""

# revision identifiers, used by Alembic.
revision = '32e121b55143'
down_revision = '46dd0ebbba0e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_performance', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_performance', 'id')
    ### end Alembic commands ###
