"""empty message

Revision ID: 35b6f16118aa
Revises: 24ad8cfb2fed
Create Date: 2014-12-20 17:06:40.875194

"""

# revision identifiers, used by Alembic.
revision = '35b6f16118aa'
down_revision = '24ad8cfb2fed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('actual_winner', sa.INTEGER(), nullable=True))
    op.drop_column('matches', 'match_ft_score')
    ### end Alembic commands ###
