"""empty message

Revision ID: 3f8785c3eea8
Revises: 5a5deb92f2a6
Create Date: 2014-11-27 21:23:28.243216

"""

# revision identifiers, used by Alembic.
revision = '3f8785c3eea8'
down_revision = '5a5deb92f2a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('default_weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_modules_name'), 'prediction_modules', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_modules_name'), table_name='prediction_modules')
    op.drop_table('prediction_modules')
    ### end Alembic commands ###
