"""empty message

Revision ID: 416d2601dbc
Revises: 43887676838e
Create Date: 2014-12-17 15:19:08.963042

"""

# revision identifiers, used by Alembic.
revision = '416d2601dbc'
down_revision = '43887676838e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savedforlater', sa.Column('predicted_winner', sa.Integer(), nullable=True))
    op.add_column('savedforlater', sa.Column('weight_form', sa.Float(), nullable=True))
    op.add_column('savedforlater', sa.Column('weight_home_away', sa.Float(), nullable=True))
    op.add_column('savedforlater', sa.Column('weight_league_position', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savedforlater', 'weight_league_position')
    op.drop_column('savedforlater', 'weight_home_away')
    op.drop_column('savedforlater', 'weight_form')
    op.drop_column('savedforlater', 'predicted_winner')
    ### end Alembic commands ###
