"""empty message

Revision ID: 42760c4629df
Revises: 1e93a7a1249d
Create Date: 2014-12-18 16:42:47.333675

"""

# revision identifiers, used by Alembic.
revision = '42760c4629df'
down_revision = '1e93a7a1249d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('league_position', sa.INTEGER(), nullable=True))
    op.create_table('moduleusersettingsset',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    ### end Alembic commands ###
