"""empty message

Revision ID: 43887676838e
Revises: 313b0da7226d
Create Date: 2014-12-15 20:29:16.925077

"""

# revision identifiers, used by Alembic.
revision = '43887676838e'
down_revision = '313b0da7226d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
