"""empty message

Revision ID: 44e2a19af084
Revises: 29ee771d5245
Create Date: 2014-11-20 11:31:57.567783

"""

# revision identifiers, used by Alembic.
revision = '44e2a19af084'
down_revision = '29ee771d5245'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('league_position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_position'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    ### end Alembic commands ###
