"""initial migration

Revision ID: 46dd0ebbba0e
Revises: None
Create Date: 2014-12-20 15:43:47.816323

"""

# revision identifiers, used by Alembic.
revision = '46dd0ebbba0e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
