"""empty message

Revision ID: 480530d497e2
Revises: 3f8785c3eea8
Create Date: 2014-11-30 13:56:42.320755

"""

# revision identifiers, used by Alembic.
revision = '480530d497e2'
down_revision = '3f8785c3eea8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictions',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('prediction', sa.Enum('home', 'away', 'draw'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['prediction_modules.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'module_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    ### end Alembic commands ###
