"""empty message

Revision ID: 480530d497e2
Revises: 3f8785c3eea8
Create Date: 2014-11-30 13:56:42.320755

"""

# revision identifiers, used by Alembic.
revision = '480530d497e2'
down_revision = '3f8785c3eea8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    ### end Alembic commands ###
