"""empty message

Revision ID: 48c56b74f757
Revises: 35b6f16118aa
Create Date: 2014-12-21 17:07:35.530127

"""

# revision identifiers, used by Alembic.
revision = '48c56b74f757'
down_revision = '35b6f16118aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('matches', 'actual_winner')
    #op.drop_column('matches', 'match_ft_score')
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('match_ft_score', sa.VARCHAR(length=8), nullable=True))
    op.add_column('matches', sa.Column('actual_winner', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
