"""empty message

Revision ID: 4ccfe9c1b8fa
Revises: 1391ee426d4
Create Date: 2014-12-23 12:56:44.406087

"""

# revision identifiers, used by Alembic.
revision = '4ccfe9c1b8fa'
down_revision = '1391ee426d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    #op.add_column('matches', sa.Column('was_played', sa.Boolean(), nullable=True))
    #op.drop_column('matches', 'actual_winner')
    #op.drop_column('matches', 'match_ft_score')
    #op.drop_column('matches', 'played')
    #op.drop_column('messages', 'author_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('author_id', sa.INTEGER(), nullable=True))
    op.add_column('matches', sa.Column('played', sa.BOOLEAN(), nullable=True))
    op.add_column('matches', sa.Column('match_ft_score', sa.VARCHAR(length=8), nullable=True))
    op.add_column('matches', sa.Column('actual_winner', sa.INTEGER(), nullable=True))
    op.drop_column('matches', 'was_played')
    ### end Alembic commands ###
