"""empty message

Revision ID: 4e025d7cb728
Revises: 7bbf1b62fe7
Create Date: 2014-12-09 11:21:25.945327

"""

# revision identifiers, used by Alembic.
revision = '4e025d7cb728'
down_revision = '7bbf1b62fe7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('league_position', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
