"""empty message

Revision ID: 5105a88a56fe
Revises: 182d5f84e276
Create Date: 2015-02-18 12:25:17.833200

"""

# revision identifiers, used by Alembic.
revision = '5105a88a56fe'
down_revision = '182d5f84e276'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'actual_winner')
    op.drop_column('matches', 'match_ft_score')
    op.drop_column('matches', 'played')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['addressee_id'], ['id'])
    op.drop_column('messages', 'author_id')
    op.drop_column('prediction_modules', 'default_weight')
    op.drop_column('savedforlater', 'weight_user_hunch')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savedforlater', sa.Column('weight_user_hunch', sa.FLOAT(), nullable=True))
    op.add_column('prediction_modules', sa.Column('default_weight', sa.FLOAT(), nullable=True))
    op.add_column('messages', sa.Column('author_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['author_id'], ['id'])
    op.add_column('matches', sa.Column('played', sa.BOOLEAN(), nullable=True))
    op.add_column('matches', sa.Column('match_ft_score', sa.VARCHAR(length=8), nullable=True))
    op.add_column('matches', sa.Column('actual_winner', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'matches', 'teams', ['actual_winner'], ['id'])
    ### end Alembic commands ###
