"""empty message

Revision ID: 51cd71dd56d1
Revises: 480530d497e2
Create Date: 2014-12-06 16:32:49.682891

"""

# revision identifiers, used by Alembic.
revision = '51cd71dd56d1'
down_revision = '480530d497e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('winner_id', sa.Integer(), nullable=True))
    op.drop_column('teams', 'league_position')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('league_position', sa.INTEGER(), nullable=True))
    op.drop_column('predictions', 'winner_id')
    ### end Alembic commands ###
