"""empty message

Revision ID: 53c739afb9d
Revises: 3fe2342ecadd
Create Date: 2014-11-24 00:13:52.250244

"""

# revision identifiers, used by Alembic.
revision = '53c739afb9d'
down_revision = '3fe2342ecadd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
