"""empty message

Revision ID: 54639320c89c
Revises: 2ca2bc7d7374
Create Date: 2014-12-18 16:56:50.511000

"""

# revision identifiers, used by Alembic.
revision = '54639320c89c'
down_revision = '2ca2bc7d7374'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('league_position', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
