"""empty message

Revision ID: 5a5deb92f2a6
Revises: 5e6dffa0cba
Create Date: 2014-11-27 20:02:26.116194

"""

# revision identifiers, used by Alembic.
revision = '5a5deb92f2a6'
down_revision = '5e6dffa0cba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('date_stamp', sa.Date(), nullable=True))
    op.add_column('matches', sa.Column('time_stamp', sa.Time(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'time_stamp')
    op.drop_column('matches', 'date_stamp')
    ### end Alembic commands ###
