"""empty message

Revision ID: 5e6dffa0cba
Revises: 53c739afb9d
Create Date: 2014-11-24 00:45:17.877917

"""

# revision identifiers, used by Alembic.
revision = '5e6dffa0cba'
down_revision = '53c739afb9d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
