"""empty message

Revision ID: 7bbf1b62fe7
Revises: 1be0b7aae23f
Create Date: 2014-12-09 11:15:57.857408

"""

# revision identifiers, used by Alembic.
revision = '7bbf1b62fe7'
down_revision = '1be0b7aae23f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('league_position', sa.INTEGER(), nullable=True))
    op.add_column('moduleusersettings', sa.Column('module_id', sa.INTEGER(), nullable=False))
    op.drop_column('moduleusersettings', 'module_name')
    ### end Alembic commands ###
