"""empty message

Revision ID: f71d76b12be
Revises: 57138b8767f7
Create Date: 2014-12-08 17:33:57.878863

"""

# revision identifiers, used by Alembic.
revision = 'f71d76b12be'
down_revision = '57138b8767f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
